### ISSUE TITLE
Game crashes upon pressing escape (in a level)

### ISSUE THREAD

**Issue by Geming400** [Alphalaneous/Pages-API#2] opened 2024-07-08 16:29 UTC
There's litterally no stack trace so I can't really know what crashed my game
[2024-07-08_18-24-47.txt](https://github.com/user-attachments/files/16131986/2024-07-08_18-24-47.txt)

**Comment by Geming400** [comment] 2024-07-09 10:33
Issue fixed

**Comment by auggeeo** [comment] 2024-07-09 16:04
If the issue is fixed please close the issue @Geming400, or @Alphalaneous because i can't.

**Comment by Geming400** [comment] 2024-07-09 19:35
I never closed an issue. My bad

**Closed as completed** 2024-07-09 19:34 UTC
